# This worklow will build and push a Docker image to Docker Hub

name: Docker

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "stagging"]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set BRANCH_NAME
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag alexandrelamberty/hortus-web-app:${{ env.BRANCH_NAME }}

      - name: Push the Docker image to Docker Hub
        run: docker push alexandrelamberty/hortus-web-app:${{ env.BRANCH_NAME }}
